AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/

DB_URIS:
  "orders:Base": postgresql://${POSTGRES_USER:postgres}:${POSTGRES_PASSWORD:password}@${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:orders}
