version: '2'
services: 
  rabbit:
    container_name: rabbit-container
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  redis:
    container_name: redis-container
    image: redis
    ports:
        - "6379:6379"
    networks:
      - app-network
  
  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: "orders"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    networks:
      - app-network

  pg-admin:
    container_name: db-admin-container
    image: dpage/pgadmin4
    ports: 
      - "8081:80"
    depends_on: 
      - postgres
    volumes:
      - ./util:/data
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin
      PGADMIN_DEFAULT_PASSWORD: p@ssword
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: system
      MONGO_INITDB_ROOT_PASSWORD: system
    networks:
      - app-network  
    volumes: 
      - mongodbdata:/data/db

  http-connector:
    container_name: http-connector-container
    build: 
      context: http-connector
    image: http-connector
    depends_on: 
      - rabbit
    ports: 
      - "8000:8000"
    environment: 
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
    networks:
      - app-network

  carts:
    container_name: carts-container
    build: 
      context: carts
    image: carts
    depends_on: 
      - rabbit
      - redis
    links: 
      - rabbit
      - redis
    environment: 
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_INDEX: "11"
    networks:
      - app-network

  orders:
    build: 
      context: orders
    image: orders
    container_name: orders-container
    depends_on:
      - rabbit
      - postgres
    environment: 
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB_NAME: "orders"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
    networks:
      - app-network
  
  products:
    build: 
      context: products 
    image: products
    container_name: products-container
    depends_on: 
      - rabbit
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGODB_DB_NAME: products
      MONGODB_HOST: mongodb
      MONGODB_POST: 27017
      MONGODB_USER: system
      MONGODB_PASSWORD: system
      MONGODB_AUTHENTICATION_BASE: admin
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodbdata:
