AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/

REDIS_URIS:
  production: 'redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}/${REDIS_INDEX:11}'
  testing: 'redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}/${REDIS_INDEX:11}'
